### ISSUE TITLE
Impossible to install in a clean virtualenv

### ISSUE THREAD

**Issue by bh** [inwx/python-client#5]
The folling error occurs if you want to install this package in a clean virtualenv:
```
    ERROR: Command errored out with exit status 1:
     command: /home/bh/projects/dns_update/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-muptp7nc/inwx-domrobot/setup.py'"'"'; __file__='"'"'/tmp/pip-install-muptp7nc/inwx-domrobot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-muptp7nc/inwx-domrobot/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-muptp7nc/inwx-domrobot/setup.py", line 2, in <module>
        from INWX.Domrobot import ApiClient
      File "/tmp/pip-install-muptp7nc/inwx-domrobot/INWX/__init__.py", line 1, in <module>
        from INWX.Domrobot import ApiClient, ApiType
      File "/tmp/pip-install-muptp7nc/inwx-domrobot/INWX/Domrobot.py", line 10, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
```

How to reproduce:
``` bash
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install inwx-domrobot==3.0.3
```
`requests` is a dependency which ins not avaibale at install time.

The bad workaround would be:
``` bash
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install requests
$ pip install inwx-domrobot==3.0.3
```

**Comment by NickUfer** [comment]
Hey, there was an issue in the package upload process. You should now be able to use version `3.0.4` like you wanted :+1:

**Comment by bh** [comment]
The issue still exists. This is not a packaging issue. Its an issue in the code structure. Try clone this repo and you make a `pip install -e .` in a clean virtual env.

**Comment by NickUfer** [comment]
Please use `pip install inwx-domrobot==3.0.4` for now. I will look into it later

**Comment by NickUfer** [comment]
Hey, with the latest version of this repo you should now be able to use `pip install -e .` in your venv.

**Comment by bh** [comment]
Sehr gut! 👍
